### ISSUE TITLE
Converting to FB account from guest accnt in Android

### ISSUE THREAD

**Issue by mellasmonforte** [topfreegames/bike-race-issues#15]
I have Android phone and pro BR.  I always used the guest account but want to change phones.  I was told I could log into fb for the first time and it wouldn't lose any information, I could then change phones and log into the same fb accnt in br and get my mp list/group list/personal best times back.  But that is not working.  When I log into fb, my mp list is gone and all my groups are all gone.
Is there anyway to keep my information?

**Comment by vkdaros** [comment]
Hi @mellasmonforte 

We will release v7.0.3 soon and we believe you'll be able to migrate your account. In order to minimize the chances of any problem happen during the process, I would suggest you to follow these steps:

1. Get your both phones to a place where internet connection is stable;
2. (New phone) Open BR-Pro, login with your Facebook account;
3. (New phone) Make sure your account doesn't have any MP races or groups (if you have to delete any race or group, kill the app and open it again to really make sure the list is empty);
4. (New phone) Kill the app;
5. (Old phone) Open BR-Pro;
6. (Old phone) Go to MP and wait until all games are loaded;
7. (Old phone) Login with your Facebook account and wait a little;
8. (New phone) Check your MP list. 

This procedure should send all your guest races to you Facebook. Unfortunately groups will not be transferred automatically and we will need to get your GuestID and FacebookID and manually change it in the database. If you don't mind, you could create a new Facebook account (or get one never used in BikeRace) and only follow steps 1; 5; 6; 7; 8 - that way, all races and groups should go to the Facebook account.
