### ISSUE TITLE
1WD in Tournaments.

### ISSUE THREAD

**Issue by GodOfBikeRace** [topfreegames/bike-race-issues#35]
Hey, it's been a year (or more) since you know that 1WD is not available in Tournaments anymore (maybe in rare special tourneys? I don't know.). When will you add that bike again together with the other prizes? 
Some people collected 36/37 bikes and 1WD is the only one bike they need.

**Comment by Trolley6969** [comment]
I emailed tfg maybe 6 months ago and they claimed that the 1wd was still available as a prize in 1* tournaments. I told them I've tried hundreds of times as have others and no one has seen it since the 1* prizes became always full bikes rather than pieces. They said they would look into it - I've heard nothing since.

**Comment by guthyerrz** [comment]
I'll take another look at this guys. I'll write here when I find a solution.

**Comment by gcamantea** [comment]
This is fixed
